pipeline:
  name: bugqa
  identifier: bugqa
  projectIdentifier: CD_Triggers_Automation
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sd
        identifier: sd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
