pipeline:
  name: remote-draftpr123
  identifier: remotedraftpr123
  projectIdentifier: kanikatest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fdg
        identifier: fdg
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo <+trigger.prTitle>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
